--1.	Crear Tres tablas Envios,EnviosNacionales,EnviosInternacionales
--Crear Tres disparadores 
--Para la tabla Envíos al insertar un nuevo registro, dependiendo del tipo de envió se deberá guardar los datos correspondientes 
--en EnviosNacionales o en EnviosInternacionales
--Para la tabla EnviosNacionales y EnviosInternacionales no se debe permitir insertar ningún registro 
--y se deberá indicar que le inserción de datos debe ser desde la tabla Envíos
USE ENVIOS_TRIGGER
GO
CREATE TABLE ENVIOS(
CODIGO		NUMERIC(5),
TIPO		VARCHAR(1),
CONSTRAINT PK_ENVIOS PRIMARY KEY (CODIGO),
CONSTRAINT CK_TIPO	CHECK (TIPO IN ('N','I'))
);
GO
CREATE TABLE E_NAL(
CODIGO NUMERIC(5),
CONSTRAINT PK_ENAL PRIMARY KEY (CODIGO),
CONSTRAINT FK_NAL_ENV FOREIGN KEY (CODIGO)
REFERENCES ENVIOS (CODIGO) ON DELETE CASCADE
);
GO
CREATE TABLE E_INT(
CODIGO NUMERIC(5),
CONSTRAINT PK_EINT PRIMARY KEY (CODIGO),
CONSTRAINT FK_INT_ENV FOREIGN KEY (CODIGO)
REFERENCES ENVIOS (CODIGO) ON DELETE CASCADE
);
GO
CREATE OR ALTER TRIGGER TR_ENVIOS
ON ENVIOS
AFTER INSERT
AS
	DECLARE @CODIGO INT
	DECLARE @TIPO VARCHAR(1)
	SET @CODIGO =	(SELECT CODIGO FROM INSERTED)
	SET @TIPO = (SELECT TIPO FROM INSERTED WHERE CODIGO=@CODIGO);
	DISABLE TRIGGER TR_INT ON E_INT;
	DISABLE TRIGGER TR_NAL ON E_NAL;
BEGIN
IF (@TIPO='I')	
	INSERT INTO E_INT VALUES(@CODIGO);
ELSE 	
	INSERT INTO E_NAL VALUES(@CODIGO);
ENABLE TRIGGER TR_INT ON E_INT;
ENABLE TRIGGER TR_NAL ON E_NAL
END
GO
CREATE OR ALTER TRIGGER TR_INT
ON E_INT
INSTEAD OF INSERT
AS
BEGIN 
RAISERROR('LA INSERCION SE DEBE REALIZAR POR MEDIO DE LA TABLA ENVIOS',16,1)
ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER TR_NAL
ON E_NAL
INSTEAD OF INSERT
AS
BEGIN 
RAISERROR('LA INSERCION SE DEBE REALIZAR POR MEDIO DE LA TABLA ENVIOS',16,1)
ROLLBACK TRANSACTION
END

INSERT INTO E_NAL VALUES(1)
SELECT * FROM E_NAL
INSERT INTO E_INT VALUES(2)
SELECT * FROM E_INT
INSERT INTO ENVIOS VALUES(1,'I')
INSERT INTO ENVIOS VALUES(2,'N')
SELECT * FROM ENVIOS
DELETE FROM ENVIOS
